### ISSUE TITLE
Won't fetch show/arc data, just episode data

### ISSUE THREAD

**Issue by alaughlin** [jwueller/jellyfin-plugin-onepace#33]
Fresh install of jellyfin and using the latest version of the plugin (1.3.2.0), and episode data downloads just fine. It just won't fetch the show/arc info.

I've attached the log, and this bit seems particularly interesting?
```
[2023-09-23 13:33:04.383 -04:00] [INF] [27] JWueller.Jellyfin.OnePace.ArcProvider: Identified Arc "{\"SeriesProviderIds\":{\"One Pace\":\"clkspj4vn000008k33lnnb4hj\",\"AniDB\":\"69\",\"AniList\":\"21\"},\"Name\":\"Season 1\",\"OriginalTitle\":null,\"Path\":null,\"MetadataLanguage\":\"en\",\"MetadataCountryCode\":\"US\",\"ProviderIds\":{},\"Year\":null,\"IndexNumber\":1,\"ParentIndexNumber\":null,\"PremiereDate\":null,\"IsAutomated\":true}" --> "null"
[2023-09-23 13:33:04.383 -04:00] [INF] [27] JWueller.Jellyfin.OnePace.ArcImageProvider: Found 0 arc image(s) for "{\"Size\":null,\"Container\":null,\"IsHD\":false,\"IsShortcut\":false,\"ShortcutPath\":null,\"Width\":0,\"Height\":0,\"ExtraIds\":[],\"DateLastSaved\":\"0001-01-01T00:00:00\",\"RemoteTrailers\":[],\"SupportsExternalTransfer\":false}" --> "[]"
[2023-09-23 13:33:04.420 -04:00] [ERR] [7] Emby.Server.Implementations.Library.LibraryManager: Error running post-scan task
System.ArgumentException: Not enough valid pictures provided to create a splashscreen!
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateCollage(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Jellyfin.Drawing.Skia.SplashscreenBuilder.GenerateSplash(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops, String outputPath)
   at Jellyfin.Drawing.Skia.SkiaEncoder.CreateSplashscreen(IReadOnlyList`1 posters, IReadOnlyList`1 backdrops)
   at Emby.Server.Implementations.Library.SplashscreenPostScanTask.Run(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.RunPostScanTasks(IProgress`1 progress, CancellationToken cancellationToken)
```

[log_20230923.log](https://github.com/jwueller/jellyfin-plugin-onepace/files/12706988/log_20230923.log)

**Comment by jwueller** [comment]
Hi, sorry for not getting to this sooner, and thanks for reporting the issue!

Could you try again with version 1.4.0.0? I fixed a few issues that might have caused this.

**Comment by turquoise-turtle** [comment]
The plugin has also stopped working for me recently. I have 1.4.0.0 installed and Jellyfin 10.8.10. Not sure if this is the same issue as OP, but in my plugin list it says Status: Not Supported.

**Comment by MidnightAnnie** [comment]
The only thing that it seems not to pull is Season info, It does update the Season posters but not the metadata.
That's what I notice anyway.

**Comment by jwueller** [comment]
@MidnightAnnie Do you still see this issue with 1.4.0.0? Could you please check what happens if you explicitly replace the existing metadata? It seems that outdated data might sometimes be retained from previous versions. If the issue persists it would be great if you could upload your log file for debugging!

**Comment by MidnightAnnie** [comment]
@jwueller Sorry for the late reply I have been busy. But indeed after a complete metadata refresh just now, it seemed to fix it.

It's only strange cos I did that the first time I installed the plugin don't know why it suddenly worked now. Maybe my setup is just slow 🐢.

**Comment by jwueller** [comment]
Interesting. I've seen something similar before, so it may be Jellyfin caching things it shouldn't, or the plugin itself getting confused by broken metadata. Thanks for the feedback!

I'll close this for now since I assume it has been fixed, but if the issue persists for either of you, please feel free to reopen this!
