### ISSUE TITLE
Plugin status Not Supported with Jellyfin 10.8.10

### ISSUE THREAD

**Issue by turquoise-turtle** [jwueller/jellyfin-plugin-onepace#46]
With the latest plugin 1.4.0.0, it says Status: Not Supported in Jellyfin 10.8.10. Trying to downgrade plugin versions to 1.32 doesn't work for sorting seasons correctly or getting the correct metadata.

**Comment by jwueller** [comment]
Version 1.4.0.0 bumped the minimum required version to [Jellyfin 10.8.13](https://github.com/jellyfin/jellyfin/releases/tag/v10.8.13) due to [a critical security vulnerability in Jellyfin 10.8.10](https://github.com/jellyfin/jellyfin/security/advisories/GHSA-9p5f-5x8v-x65m). You might have to upgrade your instance to the hotfixed release.

Please feel free to reopen this if you are still encountering issues with 10.8.13 or higher!

**Comment by jwueller** [comment]
Great, glad to hear it!

**Comment by datsoy** [comment]
Shows Unsupported on latest jellyfin 10.9.0 lsio image.

<details>
[[2024-05-12 13:11:08.188 +00:00] [INF] [1] Main: Operating system: "Ubuntu 22.04.4 LTS"
[2024-05-12 13:11:08.188 +00:00] [INF] [1] Main: Architecture: Arm64
[2024-05-12 ### 13:11:08.189 +00:00] [INF] [1] Main: 64-Bit Process: True
[2024-05-12 13:11:08.189 +00:
/00] [INF] [1] Main: User Interactive: True
[2024-05-12 13:11:08.189 +00:00] [INF] [1] Main: Processor count: 4
[2024-05-12 13:11:08.189 +00:00] [INF] [1] Main: Program data path: "/config/data"
[2024-05-12 13:11:08.189 +00:00] [INF] [1] Main: Log directory path: "/config/log"
[2024-05-12 13:11:08.189 +00:00] [INF] [1] Main: Config directory path: "/config"
[2024-05-12 13:11:08.189 +00:00] [INF] [1] Main: Cache path: "/config/cache"
[2024-05-12 13:11:08.189 +00:00] [INF] [1] Main: Web resources path: "/usr/share/jellyfin/web"
[2024-05-12 13:11:08.189 +00:00] [INF] [1] Main: Application directory: "/usr/lib/jellyfin/bin/"
[2024-05-12 13:11:08.390 +00:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "/config/cache"
[2024-05-12 13:11:09.337 +00:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2024-05-12 13:11:09.379 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.Fanart, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Fanart_11.0.0.0/Jellyfin.Plugin.Fanart.dll"
[2024-05-12 13:11:09.384 +00:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/config/data/plugins/One Pace_1.4.0.0/JWueller.Jellyfin.OnePace.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.0.0, Culture=neutral, PublicKeyToken=null'.
[2024-05-12 13:11:09.402 +00:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded assembly "Jellyfin.Plugin.OpenSubtitles, Version=20.0.0.0, Culture=neutral, PublicKeyToken=null" from "/config/data/plugins/Open Subtitles_20.0.0.0/Jellyfin.Plugin.OpenSubtitles.dll"]

<details>
