### ISSUE TITLE
Plugin not supported

### ISSUE THREAD

**Issue by giancoro** [jwueller/jellyfin-plugin-onepace#60]
After installing the plugin from your repository and restarting the server the plugin has been marked as "Not supported"

**Comment by jwueller** [comment]
Hi! Which version of Jellyfin and this plugin are you running? Jellyfin recently released a major update that required changes to almost all of the plugins. The most recent version of this plugin only works with Jellyfin 10.9 or higher.

**Comment by Ryah** [comment]
I am also getting this error on version 10.9.2.

![image](https://github.com/jwueller/jellyfin-plugin-onepace/assets/14987609/28379d10-f52b-48de-a060-f4e8e42ab1c2)

**Comment by Ashpan** [comment]
I am also facing this same issue with
Server version: 10.9.3
Web version: 10.9.3
Build version: 10.9.3

Edit: Updating to 10.9.7 seems to fix this error but now I'm running into this: https://github.com/jwueller/jellyfin-plugin-onepace/issues/71

**Comment by mattthw** [comment]
I get this with the following error log:

```
[2024-08-28 21:01:25.878 -07:00] [ERR] [4] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/matt_1/.local/share/jellyfin/plugins/InfuseSync_1.4.2.0/InfuseSync.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.10.0, Culture=neutral, PublicKeyToken=null'.
Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.10.0, Culture=neutral, PublicKeyToken=null'.
Could not load file or assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.10.0, Culture=neutral, PublicKeyToken=null'.
System.TypeLoadException: Could not load type 'MediaBrowser.Controller.Plugins.IServerEntryPoint' from assembly 'MediaBrowser.Controller, Version=10.9.10.0, Culture=neutral, PublicKeyToken=null'.
System.IO.FileNotFoundException: Could not load file or assembly 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'SQLitePCL.pretty, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
[2024-08-28 21:01:25.889 -07:00] [ERR] [4] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "/Users/matt_1/.local/share/jellyfin/plugins/One Pace_1.4.0.0/JWueller.Jellyfin.OnePace.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.10.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Could not load type 'MediaBrowser.Common.Plugins.IPluginServiceRegistrator' from assembly 'MediaBrowser.Common, Version=10.9.10.0, Culture=neutral, PublicKeyToken=null'.
[2024-08-28 21:01:25.912 -07:00] [INF] [4] Jellyfin.Networking.Manager.NetworkManager: Defined LAN subnets: ["127.0.0.1/8", "10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"]
```


Versions:

```
[2024-08-28 21:01:25.669 -07:00] [INF] [4] Main: Jellyfin version: "10.9.10"
[2024-08-28 21:01:25.694 -07:00] [INF] [4] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, /Users/matt_1/.local/share/jellyfin/log]"]
[2024-08-28 21:01:25.695 -07:00] [INF] [4] Main: Arguments: ["/Applications/Jellyfin.app/Contents/MacOS/jellyfin.dll", "--webdir", "/Applications/Jellyfin.app/Contents/Resources/jellyfin-web", "--ffmpeg", "/Applications/Jellyfin.app/Contents/MacOS/ffmpeg", "--datadir", "/Users/matt_1/.local/share/jellyfin"]
[2024-08-28 21:01:25.695 -07:00] [INF] [4] Main: Operating system: "Darwin 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:41 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8103"
```

Plugin version: latest

**Comment by jwueller** [comment]
I'll assume that this is fixed by upgrading Jellyfin. Unfortunately due to the One Pace website being currently down, pulling down the metadata won't work either way. Track #66 for nicer fallback behavior.
