### ISSUE TITLE
Plugin does not update metadata; Logs indicate 404 error

### ISSUE THREAD

**Issue by wychwitch** [jwueller/jellyfin-plugin-onepace#82]
Hello! I just installed One Pace, and my file structure matches the example given, however refreshing the metadata or re-scanning the library doesn't update the One Pace show's metadata no matter what I do. I even disabled the default metadata providers and only have One Pace providers enabled, and still no dice.

After checking the logs, I found a bunch of errors like below:
<details>
<summary> Log Snippet </summary>

```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at JWueller.Jellyfin.OnePace.WebRepository.<>c__DisplayClass6_0.<<QueryGraphQlAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at JWueller.Jellyfin.OnePace.WebRepository.QueryGraphQlAsync(String query, CancellationToken cancellationToken)
   at JWueller.Jellyfin.OnePace.WebRepository.FetchMetadataAsync(CancellationToken cancellationToken)
[2024-12-27 23:32:16.012 +00:00] [INF] [38] JWueller.Jellyfin.OnePace.SeriesProvider: Identified Series "{\"Name\":\"One Pace\",\"OriginalTitle\":null,\"Path\":\"/media/Video/Anime/One Pace\",\"MetadataLanguage\":\"en\",\"MetadataCountryCode\":\"US\",\"ProviderIds\":{},\"Year\":null,\"IndexNumber\":null,\"ParentIndexNumber\":null,\"PremiereDate\":null,\"IsAutomated\":false}" --> "null"
[2024-12-27 23:32:16.057 +00:00] [INF] [38] Jellyfin.Plugin.AniList.Providers.AniList.AniListSeriesProvider: Start AniList... Searching("One Pace")
[2024-12-27 23:32:17.938 +00:00] [ERR] [39] JWueller.Jellyfin.OnePace.WebRepository: Could not find the One Pace metadata, please report a bug at https://github.com/jwueller/jellyfin-plugin-onepace if this happened on the latest version
```

</details>

It seems as though there's some kind of error on trying to retrieve the One Pace metadata from a server. I just checked and the [one pace site](https://onepace.net/en) seems to be up, so I'm not sure what's going on? I can provide more logs if needed! (though they seem to repeat the above mostly)

I'm running One Pace version `10.9.6.13` on Jellyfin version `10.10.3`. It's being in docker on a debian server if that matters at all

If there's any other info you need let me know and I'll update!

**Comment by wychwitch** [comment]
Okay it seems like this thread might be a duplicate of #66! I'll wait before closing it however and let a maintainer decide

**Comment by MeikelLP** [comment]
FYI this repo / plugin no longer works

**Comment by wychwitch** [comment]
> FYI this repo / plugin no longer works

Yeah, there's discussion about it in #66 as to why! 

If you want the metadata get the files @IceToast helpfully made available [here!](https://github.com/jwueller/jellyfin-plugin-onepace/issues/78)
